function F=objfun_low_hd_nl(S,A,B,E,C,R_t,X,G2,H3,H2,K1,K2,K5,K4,sigma,K7,K8)
F=S'*E*sqrt(S)+(A*S+B*X)'*R_t+G2'*(R_t-S)+(R_t-S)'*H2*(R_t-S)+(C*X)'*H3*(R_t-S)+...
    (C*X)'*K1*(R_t-S).^2+((C*X).^2+sigma)'*K2*(R_t-S).^2+((R_t-S).^2)'*K4*((R_t-S).^2)+(R_t-S)'*K5*sqrt(abs(R_t-S))+K7'*(R_t-S).^3+...
    ((C*X).^2+sigma)'*K8*(R_t-S);